import type { CreateCodebaseInput } from "./validation";

/**
 * A small, real TypeScript survey used by the "Load sample survey" control.
 * It is created through the normal API, so it is a genuine stored codebase —
 * not seeded data — and can be edited, re-analyzed, or deleted like any other.
 *
 * Returns the schema *input* shape: `language` and `size` are derived on the
 * way in by `codeFileSchema`, so callers only supply `path` and `content`.
 */
export function buildSampleCodebase(): CreateCodebaseInput {
  return {
    name: "Tide Table",
    description:
      "A small harbour tide-table library: types, tide maths, formatting, tests and docs.",
    files: [
      {
        path: "src/types.ts",
        content: [
          "// Shared types for the tide table library.",
          "export interface TideEvent {",
          "  /** ISO timestamp of the event */",
          "  at: string;",
          "  /** Metres above chart datum */",
          "  height: number;",
          "  kind: 'high' | 'low';",
          "}",
          "",
          "export interface Station {",
          "  name: string;",
          "  latitude: number;",
          "  longitude: number;",
          "}",
        ].join("\n"),
      },
      {
        path: "src/index.ts",
        content: [
          "// Entry point: re-exports the public surface of the library.",
          "export { computeTides, amplitude, nextEvent } from './tides';",
          "export { formatTable, formatEvent } from './format';",
          "export type { TideEvent, Station } from './types';",
        ].join("\n"),
      },
      {
        path: "src/tides.ts",
        content: [
          "import type { Station, TideEvent } from './types';",
          "",
          "// Harmonic constants for a semi-diurnal tide.",
          "const MAIN_CONSTITUENT = 12.42;",
          "const SECOND_CONSTITUENT = 12.00;",
          "",
          "/**",
          " * Build the tide events for a station over a window of hours.",
          " * The two constituents are summed, which is crude but predictable.",
          " */",
          "export function computeTides(station: Station, hours: number): TideEvent[] {",
          "  if (hours <= 0) return [];",
          "  const events: TideEvent[] = [];",
          "  for (let hour = 0; hour < hours; hour += 1) {",
          "    const height = amplitude(station.latitude, hour);",
          "    const kind = height > 0 ? 'high' : 'low';",
          "    events.push({ at: hourLabel(hour), height, kind });",
          "  }",
          "  return events;",
          "}",
          "",
          "export function amplitude(latitude: number, hour: number): number {",
          "  const main = Math.sin((2 * Math.PI * hour) / MAIN_CONSTITUENT);",
          "  const second = Math.sin((2 * Math.PI * hour) / SECOND_CONSTITUENT);",
          "  const damp = Math.cos((latitude * Math.PI) / 180);",
          "  return (main + second) * damp;",
          "}",
          "",
          "export function nextEvent(events: TideEvent[], from: number): TideEvent | null {",
          "  if (events.length === 0) return null;",
          "  for (const event of events) {",
          "    if (event.at >= from) return event;",
          "  }",
          "  return null;",
          "}",
          "",
          "function hourLabel(hour: number): string {",
          "  const padded = hour < 10 ? '0' + hour : String(hour);",
          "  return padded + ':00';",
          "}",
        ].join("\n"),
      },
      {
        path: "src/format.ts",
        content: [
          "import type { TideEvent } from './types';",
          "",
          "export function formatEvent(event: TideEvent): string {",
          "  return event.at + '  ' + event.kind + '  ' + event.height.toFixed(2) + ' m';",
          "}",
          "",
          "export function formatTable(events: TideEvent[]): string {",
          "  if (events.length === 0) {",
          "    return 'No events';",
          "  }",
          "  return events.map(formatEvent).join('\\n');",
          "}",
        ].join("\n"),
      },
      {
        path: "tests/tides.test.ts",
        content: [
          "import { computeTides, amplitude } from '../src/tides';",
          "",
          "const STATION = { name: 'Kattegat', latitude: 57.1, longitude: 10.4 };",
          "",
          "function test(name: string, fn: () => void) {",
          "  try {",
          "    fn();",
          "    console.log('ok - ' + name);",
          "  } catch (error) {",
          "    console.log('not ok - ' + name);",
          "  }",
          "}",
          "",
          "test('empty window returns nothing', () => {",
          "  const events = computeTides(STATION, 0);",
          "  if (events.length !== 0) throw new Error('expected 0 events');",
          "});",
          "",
          "test('amplitude stays within range', () => {",
          "  for (let hour = 0; hour < 24; hour += 1) {",
          "    const value = amplitude(STATION.latitude, hour);",
          "    if (value > 2 || value < -2) throw new Error('out of range');",
          "  }",
          "});",
        ].join("\n"),
      },
      {
        path: "README.md",
        content: [
          "# Tide Table",
          "",
          "A small library for computing and formatting tide events.",
          "",
          "## Usage",
          "",
          "    import { computeTides, formatTable } from 'tide-table';",
          "    const events = computeTides({ name: 'Kattegat', latitude: 57, longitude: 10 }, 24);",
          "    console.log(formatTable(events));",
        ].join("\n"),
      },
      {
        path: "package.json",
        content: [
          "{",
          '  "name": "tide-table",',
          '  "version": "0.1.0",',
          '  "main": "src/index.ts",',
          '  "scripts": {',
          '    "test": "node tests/tides.test.ts"',
          "  }",
          "}",
        ].join("\n"),
      },
    ],
  };
}
